pretrained_model_name_or_path = "/home/ubuntu/pvbang/vb-sd-data/models/absolutereality_v181.safetensors"
caption_extension = ".txt"
resolution = "768,768"
cache_latents = true
enable_bucket = true
bucket_no_upscale = true
output_dir = "/home/ubuntu/pvbang/trainings/output"
output_name = "cosmetictubedesign"
save_precision = "fp16"
save_every_n_epochs = 1
train_batch_size = 2
max_token_length = 255
xformers = true
max_train_epochs = 10
persistent_data_loader_workers = true
gradient_checkpointing = true
mixed_precision = "fp16"
logging_dir = "/home/ubuntu/pvbang/trainings/log"
sample_every_n_epochs = 1
sample_prompts = "/home/ubuntu/pvbang/trainings/prompt.txt"
sample_sampler = "euler_a"
optimizer_type = "AdamW8bit"
learning_rate = 0.0001
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 500
lr_scheduler_num_cycles = 3
dataset_config = "/home/ubuntu/pvbang/trainings/dataset_config.toml"
unet_lr = 0.0001
text_encoder_lr = 5e-5
network_module = "networks.lora" 
network_dim = 8
network_alpha = 1